/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5dc08535-5887-497a-bc1b-43076f0f9522",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_akY1luRu9",
    "aws_user_pools_web_client_id": "7cotpntcevne7b494d1ho6nd30",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fur4lgaehfhzfo7kzp2mnctpsy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
