/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d925d6de-ccd6-415a-9234-2f59f6d8d294",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_h4VRG8hvW",
    "aws_user_pools_web_client_id": "7bg8cjl8j1hv5f034gc1seibqb",
    "oauth": {}
};


export default awsmobile;
